"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = require("fs");
const classes_1 = require("../classes");
const visualise_1 = require("../visualise");
let matter = new classes_1.StateMachine();
matter.start("solid");
let solidState = new classes_1.State("solid");
let liquidState = new classes_1.State("liquid");
let gasState = new classes_1.State("gas");
let states = [solidState, liquidState, gasState];
matter.setStates(states);
let meltTransition = new classes_1.Transition("MELT", [solidState], liquidState);
let freezeTransition = new classes_1.Transition("FREEZE", [liquidState], solidState);
let vapTransition = new classes_1.Transition("VAPORIZE", [liquidState], gasState);
let conTransition = new classes_1.Transition("CONDENSE", [gasState], liquidState);
let transitions = [meltTransition, freezeTransition, vapTransition, conTransition];
matter.setTransitions(transitions);
let smname, orientation;
smname = "matter";
orientation = "horizontal";
let dotText = (0, visualise_1.visualise)(matter, smname, orientation);
(0, fs_1.writeFileSync)("./examples/" + smname + ".dot", dotText);
(0, visualise_1.stateMachineSvgGraph)(dotText, "./examples/" + smname);
