"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = require("fs");
const classes_1 = require("../classes");
const visualise_1 = require("../visualise");
let video = new classes_1.StateMachine();
video.start("stopped");
let playState = new classes_1.State("playing");
let stopState = new classes_1.State("stopped");
let pauseState = new classes_1.State("paused");
let states = [playState, stopState, pauseState];
video.setStates(states);
let playTransition = new classes_1.Transition("PLAY", [stopState, pauseState], playState);
let stopTransition = new classes_1.Transition("STOP", [playState, pauseState], stopState);
let pauseTransition = new classes_1.Transition("PAUSE", [playState], pauseState);
let transitions = [playTransition, stopTransition, pauseTransition];
video.setTransitions(transitions);
let smname, orientation;
smname = "video";
orientation = "horizontal";
let dotText = (0, visualise_1.visualise)(video, smname, orientation);
(0, fs_1.writeFileSync)("./examples/" + smname + ".dot", dotText);
(0, visualise_1.stateMachineSvgGraph)(dotText, "./examples/" + smname);
